DJANGO_COURSE_2.xx/17-Django_Level_Four/Practice/Practice/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from PracticeApp import views

urlpatterns = [
    path('', views.index, name='index'),
    path('go_to', include('PracticeApp.urls')),
    path('admin/', admin.site.urls),
]

DJANGO_COURSE_2.xx/17-Django_Level_Four/Practice/PracticeApp/urls.py
from django.urls.conf import path
from PracticeApp import views

app_name = 'go_to'

urlpatterns = [
    path('kenobi', views.kenobi, name='kenobi'),
    path('general', views.general, name='general'),
]

DJANGO_COURSE_2.xx/17-Django_Level_Four/Practice/PracticeApp/views.py
from django.shortcuts import render

def index(request):
    add_text = {'insert_h2':'this_is_inserted', 'insert_p':22}
    return render(request, 'PracticeApp/index.html', context=add_text)

def kenobi(request):
    return render(request, 'PracticeApp/kenobi.html')
    
def general(request):
    return render(request, 'PracticeApp/general.html')

DJANGO_COURSE_2.xx/17-Django_Level_Four/Practice/templates/PracticeApp/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <meta charset="utf-8">
        <title>SW</title>
        {% block style %}
        {% endblock %}
    </head>
    <body>
        <h1>Practice</h1>
        <a href="{% url 'index' %}"><strong>Home</strong></a>
        <br>
        {% block body %}
        {% endblock %}
    </body>
</html>

DJANGO_COURSE_2.xx/17-Django_Level_Four/Practice/templates/PracticeApp/general.html
<!DOCTYPE html>
{% extends 'PracticeApp/base.html' %}
{% load static %}
    {% block style %}
        <link rel="stylesheet" href="{% static 'css_files/meme.css' %}">
    {% endblock %}

    {% block body %}
        <a href="{% url 'go_to:kenobi' %}">
            <img src="{% static 'images/general.gif' %}" alt="General 404">
        </a>
    {% endblock %}

DJANGO_COURSE_2.xx/17-Django_Level_Four/Practice/templates/PracticeApp/index.html
<!DOCTYPE html>
{% extends 'PracticeApp/base.html' %}
{% load static %}
    {% block style %}
        <link rel="stylesheet" href="{% static 'css_files/index.css' %}">
    {% endblock %}

    {% block body %}
        {% load extra_tags %}
        <h2>{{ insert_h2|upper }}</h2>
        <h2>{{ insert_h2|change:'changed' }}</h2>
        <p>{{ insert_p|add:'22' }}</p>
        <br><br>
        <a href="{% url 'go_to:kenobi' %}">Click here to start!</a>
    {% endblock %}

DJANGO_COURSE_2.xx/17-Django_Level_Four/Practice/templates/PracticeApp/kenobi.html
<!DOCTYPE html>
{% extends 'PracticeApp/base.html' %}
{% load static %}
    {% block style %}
        <link rel="stylesheet" href="{% static 'css_files/meme.css' %}">
    {% endblock %}

    {% block body %}
        <a href="{% url 'go_to:general' %}">
            <img src="{% static 'images/kenobi.gif' %}" alt="Kenobi 404">
        </a>
    {% endblock %}